# organization name, it's used to get github repo url, also in page title
name: stream-utils

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       Stream Utilities
description: node.js stream utilities
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - stream-to-array
 - destroy
 - duplex-child-process
 - streaming-json-stringify
 - raw-body
 - inflation
 - hash-stream
 - passthrough-counter
 - combine-streams
 - chunkstream
 - readall
 - contentstream
 - error-inject

# list of maintainers, this won't be sorted
maintainers:
 - name:    Doug Wilson
   github:  dougwilson   # github account, required: we link to it
   npm:     dougwilson   # npm account, required to determine lead maintainer
   twitter: blipsofadoug # twitter account, optional
   gittip:  dougwilson   # gittub badge, optional
   email:   doug@somethingdoug.com

 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   avatar:  6e33cc0412b61cc01daac23c8989003c

 - name:    Yiyu He
   github:  dead-horse
   npm:     dead_horse
   twitter: deadhorse_busi
   gittip:  dead-horse
   email:   heyiyu.deadhorse@gmail.com

 - name:    Feng Yuan
   github:  fengmk2
   npm:     fengmk2
   twitter: fengmk2
   gittip:  fengmk2
   email:   fengmk2@gmail.com

 - name:    Jerome Wagner
   github:  jeromew
   npm:     jeromew
   email:   jerome.wagner@m4x.org

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
